### ISSUE TITLE
Encryptions for images

### ISSUE THREAD

**Issue by madurangae** [konstantinullrich/crypton#12]
Hi! What is the recommended flow to encrypt images with this library? Thanks!

**Comment by konstantinullrich** [comment]
I would recommend reading the bytes of the Image and convert those to a base64 string, which you can encrypt.

I hope that helps. If you give me a few minutes, I'll try it

**Comment by konstantinullrich** [comment]
After some trying around, I concluded, It would be faster to encrypt the Images using a form of hybrid encryption.

For example, encrypt the Image with a synchronous encryption algorithm like AES and encrypt the key separately with an asynchronous algorithm. I know it's an extra step, but I'd reckon it'll improve the performance of your application.

**Comment by madurangae** [comment]
Thanks for the great tip!! It makes total sense to use the hybrid approach
you have mentioned.
