### ISSUE TITLE
Can we generate RSA public key from PEM?

### ISSUE THREAD

**Issue by adonese** [konstantinullrich/crypton#22]
Currently the library only generates a random RSA key and use it for encryption. Some use cases (my current use case) relies on an existing rsa public key, and the idea is to use the existing public key to encrypt a message.

Can this use case be supported? Thanks!

**Comment by konstantinullrich** [comment]
Technically you could use the `RSAPrivateKey.fromString` Function for that. 
But I could add a `.fromPEM` function.

**Comment by adonese** [comment]
Unfortunately, i'm not that good in dart / flutter -- and you can correct
me if i'm wrong. This library is testable by `flutter test` and unlike
other libraries, it doesn't rely on OS specific functionality for that.

That's why i think it is cool, plus also the simple API too!

PS. Can that by RSAPublic.fromString()?

**Comment by konstantinullrich** [comment]
No worries, I created this lib to make Encryption easy and accessible for everyone :)

Yes, thanks to Dart this lib is platform-independent.
To test this lib you simply clone the repo and run `pub test`

To create a public key using a string you could use `RSAPublic.fromString()`

You can also look at the [API Dokumentation](https://pub.dev/documentation/crypton/latest/crypton/crypton-library.html) for more information.

**Comment by adonese** [comment]
So great! I used `RSAPublic.fromString()` and it just worked!
