### ISSUE TITLE
Null safety release

### ISSUE THREAD

**Issue by rokk4** [konstantinullrich/crypton#23]
First of all, thank you for this useful package. @konstantinullrich It provides a lot of value.

Now my question is, when are you going with the Dart null safety train?

asn1lib & pointycastle have null safety releases, so that should not be a problem?

What causes a problem, is that if you are using crypton, the project gets stuck on old versions of asn1lib & pointycastle, which are also used by other packages, which therefore also can't be updated :(

**Comment by konstantinullrich** [comment]
I'll hop on it right away :)

**Comment by konstantinullrich** [comment]
Okay, I did the migration. 

But, we have to wait for https://github.com/bcgit/pc-dart/pull/81 to be merged. The Migration to null safety of the pointycastle wasn't done right, which causes the Curve Construction of the Elliptic Curve Part in Crypton to fail.

**Comment by savs90** [comment]
This will be super. Thanks for the great work @konstantinullrich  !

**Comment by konstantinullrich** [comment]
It seems that the PR has been merged. We only need to wait until the Legion uploads the latest version (pointycastle-3.0.0-nullsafety.3 I guess) to pub.dev.
