### ISSUE TITLE
Examples in Documentation need updating to show new functions

### ISSUE THREAD

**Issue by kanyeceejayA** [konstantinullrich/crypton#30]
createSignature and verifySignature are currently deprecated but they appear in the example shown on github, I thought it would be great if we replaced these with examples using createSHA256Signature since it doesn't use strings and can be tricky to switch to.

**Comment by konstantinullrich** [comment]
Sounds reasonable. I'll fix it asap.

Meanwhile you can grab the code you are looking for from the Unit Tests.
