### ISSUE TITLE
Update Readme to point to pointycastle package

### ISSUE THREAD

**Issue by FMorschel** [konstantinullrich/crypton#42]
On Readme, there is the following:

> This library is a simplified interface to interact with the [pointy castle](https://github.com/PointyCastle/pointycastle)

However, the current link is an old GitHub project that is no longer working. Please point to the actual pub.dev package as it has the repository link on the right side.

New link: https://pub.dev/packages/pointycastle

**Comment by konstantinullrich** [comment]
You are right. I'll get on it right away 😃
