### ISSUE TITLE
Make a way to pull keypair from PEM files

### ISSUE THREAD

**Issue by AKushWarrior** [konstantinullrich/crypton#5]
You should have a way to use external keypairs so people are not limited to auto-generation.

**Comment by konstantinullrich** [comment]
I'll see what I can do. Because I also want to support Web

**Comment by AKushWarrior** [comment]
The "File" class is still supported on web.

If this is easier, you can have users pass a PEM String (the result of reading a file) and use that.

If you want to piggyback some code (so to speak), the deprecated RsaCrypt class in steel_crypt has methods for this.

**Comment by konstantinullrich** [comment]
@AKushWarrior please take a look at my latest commit on this issues feature branch

**Comment by AKushWarrior** [comment]
Looks good to me. On mobile, so I can't run tests, but it should work.
