### ISSUE TITLE
Adjustable Key size 

### ISSUE THREAD

**Issue by melewetwo** [konstantinullrich/crypton#7]
Make the key size adjustable.
It should be possible to create a keypair using  

`RSAKeypair.fromRandom() `

with adjustable key size.

maybe using an optional named param that defaults to 2048?

`RSAKeypair.fromRandom({int keySize=2048})`

**Comment by konstantinullrich** [comment]
Good Idea

Will be done :)

**Comment by melewetwo** [comment]
maybe even default to 4096 bits: 
It is recommend to use at least 3072 bits if security is required beyond 2030:
https://en.wikipedia.org/wiki/Key_size#:~:text=NIST%20recommends%202048%2Dbit%20keys,to%20256%2Dbit%20symmetric%20keys.

**Comment by konstantinullrich** [comment]
Then we'll default to 3072 :)

**Comment by melewetwo** [comment]
just created a pull request, but didn't read your message before - i used 4096 as default.
I can change it if you want to.

**Comment by konstantinullrich** [comment]
No worries
I'll merge if the tests pass

**Comment by konstantinullrich** [comment]
I reviewed your PR
